spring.application.name=soundscape-app
spring.ai.openai.api-key=${GEMINI_API_KEY:}
spring.ai.openai.base-url=${GEMINI_OPENAI_BASE_URL:https://generativelanguage.googleapis.com}
spring.ai.openai.chat.completions-path=${GEMINI_OPENAI_CHAT_COMPLETIONS_PATH:/v1beta/openai/chat/completions}
spring.ai.openai.chat.options.model=${GEMINI_MODEL:gemini-2.5-flash}
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true

logging.level.org.springframework.security=INFO
spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}
spring.data.redis.password=${REDIS_PASSWORD}
jwt.refresh.expiration=${JWT_REFRESH_EXPIRATION}
jwt.secret=${JWT_SECRET}
jwt.accessTokenExpiration=${JWT_ACCESS_TOKEN_EXPIRATION}
spring.mail.host=${MAIL_HOST}
spring.mail.port=${MAIL_PORT}
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


google.client.id=${GOOGLE_CLIENT_ID}
google.client.secret=${GOOGLE_CLIENT_SECRET}

google.callback.url=${GOOGLE_CALLBACK_URL}
# application.properties
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB
aws.s3.access.key.id=${AWS_S3_ACCESS_KEY_ID}
aws.s3.secret.access.key=${AWS_S3_SECRET_ACCESS_KEY}
aws.s3.region=${AWS_S3_REGION}
aws.s3.bucket.name=${AWS_S3_BUCKET_NAME}
aws.s3.asset.music=asset/music/
aws.s3.asset.image=asset/image/
aws.s3.asset.video=asset/video/
app.cdn.base-url=${APP_CDN_BASE_URL:https://cdn.vantrandigital.id.vn}
#spring.profiles.active=dev
# --- HikariCP Connection Pool --- 1 vCPU 1GB RAM:
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.max-lifetime=1200000
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.pool-name=HikariSpotifyPool

app.web.base-url=${APP_WEB_BASE_URL}
app.email.verification-token-ttl=${EMAIL_VERIFICATION_TOKEN_TTL}
app.mail.provider=${MAIL_PROVIDER}
app.mail.from=${MAIL_FROM}
app.mail.fail-on-error=${MAIL_FAIL_ON_ERROR}

spring.mvc.pathmatch.matching-strategy=ant_path_matcher
